[logging]
host = "127.0.0.1"
port = 8316
message_format = "%(asctime)s.%(msecs)03d %(name)s [%(levelname)s]: %(message)s"
date_format = "%Y/%m/%d %H:%M:%S"

[multiprocessing]
start_method = "spawn" # or "fork". If using "fork", you may face freeze problems caused by multi process threading. 

[commands]
[commands.keyboard]
shutdown = "<ctrl>+<shift>+q" # check `pynput` hot key format.